/**
 * Multiplayer wire protocol: types and runtime validators.
 *
 * Source of truth for the relay server (server/) and the engine client.
 * Human-readable description: docs/multiplayer-protocol.md.
 *
 * Zero dependencies and no Node-specific APIs, so it can be imported from the
 * server, from tests, or from a browser tool.
 *
 * Transport: WebSocket, one JSON object per message.
 * Units: positions in world pixels, velocity in px/s, acceleration in px/s^2,
 * rotation in RADIANS (same as the engine's TransformComponent.rotation).
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Sent by clients in `hello.version`. Bump on any breaking change. */
export const PROTOCOL_VERSION = 1;

/** Largest accepted raw message, in bytes (UTF-8). Larger ones are dropped. */
export const MAX_MESSAGE_BYTES = 16 * 1024;

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

/** World-space vector (pixels, px/s or px/s^2 depending on the field). */
export interface Vec2 {
  x: number;
  y: number;
}

/** Short random id assigned by the server on connect. */
export type PlayerId = string;

/** `"<playerId>:<counter>"`, generated by the owner of the entity. */
export type NetId = string;

/**
 * Fields common to every message. Payload fields are added by each message.
 *
 * - `from` is stamped by the server and overwrites whatever the client sent,
 *   so it cannot be spoofed. Clients may omit it (see `isClientEnvelope`).
 * - `to`, when set, makes the message direct; otherwise it is broadcast to
 *   everyone except the sender.
 * - `seq` is a per-sender counter; receivers drop stale `state` messages.
 * - `ts` is the sender's clock in milliseconds (informational, not synced).
 */
export interface Envelope<T extends string> {
  t: T;
  from: PlayerId;
  to?: PlayerId;
  seq: number;
  ts: number;
}

/** Kinematic state of a networked entity. */
export interface Kinematics {
  pos: Vec2;
  vel: Vec2;
  /** Radians. */
  rot: number;
  acc: Vec2;
}

/** Initial state carried by `spawn` and `snapshot`. Extra script data allowed. */
export interface EntityState extends Kinematics {
  hp?: number;
  [key: string]: unknown;
}

/** One entity inside a `snapshot`. */
export interface SnapshotEntity {
  netId: NetId;
  owner: PlayerId;
  script: string;
  state: EntityState;
}

/** Room-wide settings, controlled by the host. */
export interface RoomSettings {
  pvp: boolean;
}

// ---------------------------------------------------------------------------
// Session messages
// ---------------------------------------------------------------------------

/** Server -> client, direct. First message a client receives (server-only). */
export interface Welcome extends Envelope<"welcome"> {
  playerId: PlayerId;
  hostId: PlayerId;
  peers: PlayerId[];
}

/** Server -> clients (server-only). A new player connected. */
export interface PeerJoined extends Envelope<"peer_joined"> {
  playerId: PlayerId;
}

/** Server -> clients (server-only). A player disconnected. */
export interface PeerLeft extends Envelope<"peer_left"> {
  playerId: PlayerId;
}

/** Server -> clients (server-only). Host left; rule 5: new host adopts entities. */
export interface HostChanged extends Envelope<"host_changed"> {
  hostId: PlayerId;
}

/** Client -> server. Sent once after connecting. */
export interface Hello extends Envelope<"hello"> {
  name: string;
  /** Must equal PROTOCOL_VERSION. */
  version: number;
}

// ---------------------------------------------------------------------------
// Entity messages
// ---------------------------------------------------------------------------

/** Owner only (rule 3). Announces a new networked entity. */
export interface Spawn extends Envelope<"spawn"> {
  netId: NetId;
  owner: PlayerId;
  script: string;
  state: EntityState;
}

/** Owner only (rule 3). Removes a networked entity. */
export interface Despawn extends Envelope<"despawn"> {
  netId: NetId;
}

/** Owner only. Periodic kinematic correction for the owner's entity (rule 1). */
export interface State extends Envelope<"state">, Kinematics {
  netId: NetId;
}

// ---------------------------------------------------------------------------
// Combat messages
// ---------------------------------------------------------------------------

/** Shooter (bullet owner) only. A bullet was fired (rules 1 and 3). */
export interface Fire extends Envelope<"fire"> {
  bulletNetId: NetId;
  shooterNetId: NetId;
  pos: Vec2;
  vel: Vec2;
  dmg: number;
}

/**
 * Sent only by the owner of `target`, from its own collision detection
 * (rule 4). Everyone else applies `newHp` and never computes HP themselves.
 */
export interface Damage extends Envelope<"damage"> {
  target: NetId;
  amount: number;
  newHp: number;
  /** NetId of the bullet or entity that caused it. */
  source?: NetId;
}

/** Sent only by the owner of `netId` (rule 4), usually after hp <= 0. */
export interface Death extends Envelope<"death"> {
  netId: NetId;
  /** PlayerId of the killer, if any. */
  killer?: PlayerId;
}

// ---------------------------------------------------------------------------
// Loot messages
// ---------------------------------------------------------------------------

/** Any player -> the loot's owner (host), direct. Asks to pick up loot. */
export interface PickupRequest extends Envelope<"pickup_request"> {
  lootNetId: NetId;
}

/** Loot owner (host) only, broadcast. First request wins; `by` gets the item. */
export interface LootTaken extends Envelope<"loot_taken"> {
  lootNetId: NetId;
  by: PlayerId;
}

// ---------------------------------------------------------------------------
// Join / settings messages
// ---------------------------------------------------------------------------

/** New player, broadcast. Only the host answers, with a direct `snapshot`. */
export interface SnapshotRequest extends Envelope<"snapshot_request"> {}

/** Host only, direct (`to` = requester). Full world state for a late joiner. */
export interface Snapshot extends Envelope<"snapshot"> {
  entities: SnapshotEntity[];
  settings: RoomSettings;
}

/** Host only, broadcast. Changes room-wide settings. */
export interface RoomSettingsMsg extends Envelope<"room_settings"> {
  pvp: boolean;
}

// ---------------------------------------------------------------------------
// Custom messages
// ---------------------------------------------------------------------------

/**
 * Any player, broadcast or direct. Opaque script-level message: the relay only
 * checks `type` and forwards `data` untouched.
 */
export interface Custom extends Envelope<"custom"> {
  /** Script-defined message name (1-64 chars). */
  type: string;
  data?: unknown;
}

// ---------------------------------------------------------------------------
// Unions and maps
// ---------------------------------------------------------------------------

export type Message =
  | Welcome
  | PeerJoined
  | PeerLeft
  | HostChanged
  | Hello
  | Spawn
  | Despawn
  | State
  | Fire
  | Damage
  | Death
  | PickupRequest
  | LootTaken
  | SnapshotRequest
  | Snapshot
  | RoomSettingsMsg
  | Custom;

export type MessageType = Message["t"];

export type MessageByType = { [M in Message as M["t"]]: M };

/** Types only the server may originate. The server drops them from clients. */
export const SERVER_ONLY_TYPES = [
  "welcome",
  "peer_joined",
  "peer_left",
  "host_changed",
] as const;

export type ServerOnlyType = (typeof SERVER_ONLY_TYPES)[number];

export function isServerOnlyType(t: unknown): t is ServerOnlyType {
  return (SERVER_ONLY_TYPES as readonly unknown[]).indexOf(t) !== -1;
}

// ---------------------------------------------------------------------------
// Primitive checks (private)
// ---------------------------------------------------------------------------

type Check = (v: unknown) => boolean;

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isString(v: unknown): v is string {
  return typeof v === "string" && v.length > 0;
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

function isNonNegInt(v: unknown): v is number {
  return typeof v === "number" && Number.isInteger(v) && v >= 0;
}

function isBoolean(v: unknown): v is boolean {
  return typeof v === "boolean";
}

function isVec2(v: unknown): v is Vec2 {
  return isObject(v) && isFiniteNumber(v.x) && isFiniteNumber(v.y);
}

function isPlayerId(v: unknown): v is PlayerId {
  return isString(v) && v.indexOf(":") === -1;
}

function isNetId(v: unknown): v is NetId {
  return typeof v === "string" && /^[^:]+:\d+$/.test(v);
}

function isPlayerIdArray(v: unknown): v is PlayerId[] {
  return Array.isArray(v) && v.every(isPlayerId);
}

function optional(check: Check): Check {
  return (v) => v === undefined || check(v);
}

function isKinematics(v: Record<string, unknown>): boolean {
  return isVec2(v.pos) && isVec2(v.vel) && isFiniteNumber(v.rot) && isVec2(v.acc);
}

function isEntityState(v: unknown): v is EntityState {
  return isObject(v) && isKinematics(v) && optional(isFiniteNumber)(v.hp);
}

function isSnapshotEntity(v: unknown): v is SnapshotEntity {
  return (
    isObject(v) &&
    isNetId(v.netId) &&
    isPlayerId(v.owner) &&
    isString(v.script) &&
    isEntityState(v.state)
  );
}

function isRoomSettings(v: unknown): v is RoomSettings {
  return isObject(v) && isBoolean(v.pvp);
}

// ---------------------------------------------------------------------------
// Envelope validators
// ---------------------------------------------------------------------------

/** Envelope fields except `from` (what a client is expected to send). */
function hasClientEnvelopeFields(v: unknown): v is Record<string, unknown> {
  return (
    isObject(v) &&
    isString(v.t) &&
    optional(isPlayerId)(v.to) &&
    isNonNegInt(v.seq) &&
    isFiniteNumber(v.ts)
  );
}

/** Full envelope as seen by receivers: `from` is present (server-stamped). */
export function isEnvelope(v: unknown): v is Envelope<string> {
  return hasClientEnvelopeFields(v) && isPlayerId(v.from);
}

/**
 * Envelope as sent by a client: `from` is optional because the server
 * overwrites it anyway. The server validates with this, stamps `from`,
 * then forwards.
 */
export function isClientEnvelope(
  v: unknown,
): v is Omit<Envelope<string>, "from"> & { from?: PlayerId } {
  return hasClientEnvelopeFields(v) && optional(isPlayerId)(v.from);
}

// ---------------------------------------------------------------------------
// Payload checks per message type (private)
// ---------------------------------------------------------------------------

const payloadChecks: { [K in MessageType]: (v: Record<string, unknown>) => boolean } = {
  welcome: (v) => isPlayerId(v.playerId) && isPlayerId(v.hostId) && isPlayerIdArray(v.peers),
  peer_joined: (v) => isPlayerId(v.playerId),
  peer_left: (v) => isPlayerId(v.playerId),
  host_changed: (v) => isPlayerId(v.hostId),
  hello: (v) => isString(v.name) && isNonNegInt(v.version),
  spawn: (v) =>
    isNetId(v.netId) && isPlayerId(v.owner) && isString(v.script) && isEntityState(v.state),
  despawn: (v) => isNetId(v.netId),
  state: (v) => isNetId(v.netId) && isKinematics(v),
  fire: (v) =>
    isNetId(v.bulletNetId) &&
    isNetId(v.shooterNetId) &&
    isVec2(v.pos) &&
    isVec2(v.vel) &&
    isFiniteNumber(v.dmg),
  damage: (v) =>
    isNetId(v.target) &&
    isFiniteNumber(v.amount) &&
    isFiniteNumber(v.newHp) &&
    optional(isNetId)(v.source),
  death: (v) => isNetId(v.netId) && optional(isPlayerId)(v.killer),
  pickup_request: (v) => isNetId(v.lootNetId),
  loot_taken: (v) => isNetId(v.lootNetId) && isPlayerId(v.by),
  snapshot_request: () => true,
  snapshot: (v) =>
    Array.isArray(v.entities) && v.entities.every(isSnapshotEntity) && isRoomSettings(v.settings),
  room_settings: (v) => isBoolean(v.pvp),
  custom: (v) => isString(v.type) && v.type.length <= 64,
};

function guard<T extends MessageType>(t: T): (v: unknown) => v is MessageByType[T] {
  return (v: unknown): v is MessageByType[T] =>
    isEnvelope(v) && v.t === t && payloadChecks[t](v as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// One exported validator per message
// ---------------------------------------------------------------------------

export const isWelcome = guard("welcome");
export const isPeerJoined = guard("peer_joined");
export const isPeerLeft = guard("peer_left");
export const isHostChanged = guard("host_changed");
export const isHello = guard("hello");
export const isSpawn = guard("spawn");
export const isDespawn = guard("despawn");
export const isState = guard("state");
export const isFire = guard("fire");
export const isDamage = guard("damage");
export const isDeath = guard("death");
export const isPickupRequest = guard("pickup_request");
export const isLootTaken = guard("loot_taken");
export const isSnapshotRequest = guard("snapshot_request");
export const isSnapshot = guard("snapshot");
export const isRoomSettingsMsg = guard("room_settings");
export const isCustom = guard("custom");

/** Validator lookup by message type. */
export const validators: { [K in MessageType]: (v: unknown) => v is MessageByType[K] } = {
  welcome: isWelcome,
  peer_joined: isPeerJoined,
  peer_left: isPeerLeft,
  host_changed: isHostChanged,
  hello: isHello,
  spawn: isSpawn,
  despawn: isDespawn,
  state: isState,
  fire: isFire,
  damage: isDamage,
  death: isDeath,
  pickup_request: isPickupRequest,
  loot_taken: isLootTaken,
  snapshot_request: isSnapshotRequest,
  snapshot: isSnapshot,
  room_settings: isRoomSettingsMsg,
  custom: isCustom,
};

function hasKnownType(v: unknown): v is { t: MessageType } {
  return (
    isObject(v) &&
    typeof v.t === "string" &&
    Object.prototype.hasOwnProperty.call(validators, v.t)
  );
}

/** True when `v` is a complete, well-formed message of a known type. */
export function validateMessage(v: unknown): v is Message {
  if (!hasKnownType(v)) return false;
  return (validators[v.t] as (x: unknown) => boolean)(v);
}

/**
 * Validates a message as sent by a client (`from` optional). Same as
 * `validateMessage` otherwise. Server-side use: validate, stamp `from`, forward.
 */
export function validateClientMessage(v: unknown): boolean {
  if (!hasKnownType(v) || !isClientEnvelope(v)) return false;
  return payloadChecks[v.t](v as unknown as Record<string, unknown>);
}

/**
 * Parses a raw WebSocket text frame. Returns null if it is larger than
 * MAX_MESSAGE_BYTES, is not valid JSON, or is not a valid message.
 */
export function parseMessage(raw: string): Message | null {
  if (typeof raw !== "string") return null;
  // UTF-16 length is a lower bound on UTF-8 bytes: cheap early reject.
  if (raw.length > MAX_MESSAGE_BYTES) return null;
  if (new TextEncoder().encode(raw).length > MAX_MESSAGE_BYTES) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  return validateMessage(parsed) ? parsed : null;
}

// ---------------------------------------------------------------------------
// Net ID helpers
// ---------------------------------------------------------------------------

/** Builds a NetId from the owner's playerId and its local counter. */
export function makeNetId(playerId: PlayerId, counter: number): NetId {
  return `${playerId}:${counter}`;
}

/** Returns the playerId that originally generated `netId` (split on last ':'). */
export function netIdOwner(netId: NetId): PlayerId {
  return netId.slice(0, netId.lastIndexOf(":"));
}
